# -*- coding: utf-8 -*-
"""for mary jane.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5UeXAU1g3h_8Ib4AClpTcgNK_9PBlzm
"""

pessoa = str(input("Insira seu nome: "))
contador = 0

if pessoa == "Pookie" or pessoa == "Maria Júlia" or pessoa == "Maria":
  print("Eu te amo")

  while pessoa == "Pookie" or pessoa == "Maria Júlia" or pessoa == "Maria":
    pergunta=str(input("Você deseja que eu continue te amando (responde com SIM ou NAO) ? SIM/NAO   "))
    contador += 1

    if pergunta == "SIM":
      print("Eu te amo")

    elif pergunta ==  "NAO":
      print("Ok, mas eu continuo te amando")
      break

    if contador >= 4:
      print("EU VOU TE AMAR PRA SEMPRE")

else:
  print("Sai de perto")