# -*- coding: utf-8 -*-
"""for pookie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5UeXAU1g3h_8Ib4AClpTcgNK_9PBlzm
"""

import streamlit as st

st.title("Responde Certinho 😉")

# Entrada do nome
pessoa = st.text_input("Insira seu nome:")

# Inicializa variáveis de sessão
if "contador" not in st.session_state:
    st.session_state.contador = 0
if "continuar" not in st.session_state:
    st.session_state.continuar = True

# Verifica se é a pessoa certa
if pessoa in ["Pookie", "Maria Júlia", "Maria"]:
    st.success("Eu te amo 💕")

    # Enquanto ela quiser continuar
    if st.session_state.continuar:

        st.write("Você deseja que eu continue te amando (responde com SIM ou NAO)?")

        col1, col2 = st.columns(2)

        with col1:
            if st.button("💖 SIM"):
                st.session_state.contador += 1
                st.write("Eu te amo 💖")

                if st.session_state.contador >= 4:
                    st.balloons()
                    st.error("EU VOU TE AMAR PRA SEMPRE 💘")
                    st.session_state.continuar = False

        with col2:
            if st.button("💔 NAO"):
                st.warning("Ok, mas eu continuo te amando 😘")
                st.session_state.continuar = False
    else:
        st.write("Fim do nosso amor... (mas eu ainda te amo) 💞")

else:
    if pessoa:
        st.write("Sai de perto 😠")
