# -*- coding: utf-8 -*-
"""for pookie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5UeXAU1g3h_8Ib4AClpTcgNK_9PBlzm
"""

import streamlit as st

st.title("Responde De Vdd 😉")

pessoa = st.text_input("Insira seu nome:")
contador = 0

if pessoa in ["Pookie", "Maria Júlia", "Maria"]:
    st.success("Eu te amo 💕")
    
    while pessoa ["Pookie", "Maria Júlia", "Maria"]:  
        pergunta = st.text_input("Você deseja que eu continue te amando? (responde com SIM ou NAO): ")
        contador += 1
        
        if pergunta == "SIM":
            st.write("Eu te amo 💖")

        elif pergunta == "NAO":
            st.warning("Ok, mas eu continuo te amando 😘")
            break

        if contador >= 4:
            st.success("EU VOU TE AMAR PRA SEMPRE 💘")

else:
    st.warning("Sai de perto 😠")
