# -*- coding: utf-8 -*-
"""for pookie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5UeXAU1g3h_8Ib4AClpTcgNK_9PBlzm
"""

import streamlit as st

st.title("Responde Certinho 🤗")

# entrada do nome
pessoa = st.text_input("Insira seu nome:")

# inicializa contador na sessão, se ainda não existir
if "contador" not in st.session_state:
    st.session_state.contador = 0

# lógica principal
if pessoa in ["Pookie", "Maria Júlia", "Maria"]:
    st.success("Eu te amo 💕")

    # mostra pergunta só se ainda não respondeu "NAO"
    if "acabou" not in st.session_state or not st.session_state.acabou:
        pergunta = st.text_input("Você deseja que eu continue te amando? (responde com SIM ou NAO):")

        if pergunta.upper() == "SIM":
            st.session_state.contador += 1
            st.write("Eu te amo 💖")

            # se chegar a 4 respostas "SIM"
            if st.session_state.contador >= 4:
                st.balloons()
                st.error("EU VOU TE AMAR PRA SEMPRE 💘")
                st.session_state.acabou = True

        elif pergunta.upper() == "NAO":
            st.warning("Ok, mas eu continuo te amando 😘")
            st.session_state.acabou = True
else:
    if pessoa:
        st.write("Sai de perto 😠")
